POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRlcm1vdCIsImlkIjoiNjUwZDU2NDgwOGRmOWVmMDVmMTRmODk5IiwiaWF0IjoxNjk1Mzg4Njg2LCJleHAiOjE2OTUzOTIyODZ9.V1wKwu_fNNIdXw49s1crMoX23RNVapGfFDoMa1B2VXg

{
  "title": "Running out of title names again2",
  "author": "Teddy Tedderson",
  "url": "/testblog/anothertest",
  "likes": 1235,
  "userId": "650d564808df9ef05f14f899"
}
