POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "test_user2",
    "name": "Test username",
    "password": "test_password"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "test_user2",
    "password": "test_password"
}

# {
#     "username": "dermot",
#     "password": "Dermot'sPassword"
# }